#!/bin/bash
# Hyperbox - Virtual Infrastructure Manager
# Copyright (C) 2013 Maxime Dor
# 
# http://kamax.io/hbox/
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation under version 2 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

java -splash:icons/login-header.png -cp bin/*:lib/*:modules/* io.kamax.hboxc.HyperboxClientApplicationStart "$@"
